import Head from "next/head";
import Header from "@/components/Header";
import Article from "@/components/Article";
import Weather from "@/components/Weather ";
import Stock from "@/components/Stock";
import Chart from "@/components/Chart";


interface Article {
  title: string;
  description: string;
  urlToImage: string;
  url: string;
}

interface HomeProps {
  topArticles: Article[];
  weatherData: {
    main: {
      temp: number;
    };
    weather: {
      description: string;
      icon: string;
    }[];
  };
}

export default function Home(props: HomeProps) {
  console.log(props.topArticles);
  console.log(props.weatherData);

  const [mainArticle, ...otherArticles] = props.topArticles;

  return (
    <>
      <Head>
        <title>THE NEWS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
        <div className="mx-8 sm:mx-12 lg:mx-32 mt-4 sm:mt-6 md:mt-10 flex gap-5">
          <div>
            {/* Main article */}
            <div className="list-none">
              <Article article={mainArticle} />
            </div>
            {/* Other articles */}
            <ul className="grid grid-cols-3 gap-10">
              {otherArticles.map((article, id) => (
                <Article key={id} article={article} />
              ))}
            </ul>
          </div>
          <div>
            {/* weather */}
            <Weather weatherData={props.weatherData} />
            {/* Stockchart */}
            <Stock />
            <Chart />
          </div>
        </div>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const newsApiRes = await fetch(
    `https://newsapi.org/v2/top-headlines?country=us&pageSize=10&apiKey=d348775997b145a8be32991e670bef43`
  );
  const newsApiJson = await newsApiRes.json();
  const topArticles: Article[] = newsApiJson?.articles;

  const API_key = "717d7fee9968095039fb3bf151156a94";
  const API_URL = `https://api.openweathermap.org/data/2.5/weather?lat=33.8218&lon=130.5415&appid=${API_key}&lang=ja&units=metric`;
  const weatherRes = await fetch(API_URL);
  const weatherJson = await weatherRes.json();
  const weatherData = weatherJson;

  return {
    props: {
      topArticles,
      weatherData,
    },
    revalidate: 60 * 10,
  };
};
