import Head from "next/head";
import Header from "@/components/Header";
import Article from "@/components/Article";

interface Article {
  title: string;
  description: string;
  urlToImage: string;
  url: string;
}

interface HomeProps {
  topArticles: Article[];
}

export default function Home(props: HomeProps) {
  console.log(props.topArticles);

  const [mainArticle, ...otherArticles] = props.topArticles;

  return (
    <>
      <Head>
        <title>THE NEWS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
        <div className="mx-8 sm:mx-12 lg:mx-32 mt-4 sm:mt-6 md:mt-10">
          <div>
            {/* Main article */}
            <div className="list-none">
              <Article article={mainArticle} />
            </div>
            {/* Other articles */}
            <ul className="grid grid-cols-3 gap-10">
              {otherArticles.map((article, id) => (
                <Article key={id} article={article} />
              ))}
            </ul>
          </div>
          <div>{/* chart */}</div>
        </div>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const topRes = await fetch(
    `https://newsapi.org/v2/top-headlines?country=us&pageSize=10&apiKey=d348775997b145a8be32991e670bef43`
  );
  const topJson = await topRes.json();
  const topArticles: Article[] = topJson?.articles;

  return {
    props: {
      topArticles,
    },
    revalidate: 60 * 10,
  };
};
